import json, subprocess, os, sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
from common import tok

HERE = os.path.dirname(os.path.abspath(__file__))


def js(v):
    return json.dumps(v, ensure_ascii=False)


def fmt_examples(fn, examples):
    lines = []
    for args, exp in examples:
        a = ', '.join(js(x) for x in args)
        lines.append(f"{fn}({a})  // returns {js(exp)}")
    return '```javascript\n' + '\n'.join(lines) + '\n```'


def verify_examples(folder, fn, examples):
    spec = {'functionName': fn, 'tests': [{'args': a, 'expected': e} for a, e in examples]}
    p = os.path.join(folder, 'examples.json')
    json.dump(spec, open(p, 'w'))
    out = subprocess.run(['node', os.path.join(HERE, 'harness.mjs'), p, os.path.join(folder, 'ref.js')], capture_output=True, text=True, cwd=HERE)
    first = out.stdout.strip().split('\n')[-1]
    n = len(examples)
    assert first.startswith(f'{n}/{n}'), (folder, out.stdout, out.stderr)


def build_cases(group_dir, table, trailer, notes_extra):
    cases = []
    for cid, spec in table.items():
        folder = os.path.join(HERE, group_dir, cid)
        verify_examples(folder, spec['fn'], spec['examples'])
        prompt = spec['prompt'].replace('{examples}', fmt_examples(spec['fn'], spec['examples'])).replace('{trailer}', trailer)
        tests = json.load(open(os.path.join(folder, 'tests.json')))
        assert tests['functionName'] == spec['fn']
        # re-run reference against the final tests
        out = subprocess.run(['node', os.path.join(HERE, 'harness.mjs'), os.path.join(folder, 'tests.json'), os.path.join(folder, 'ref.js')], capture_output=True, text=True, cwd=HERE)
        n = len(tests['tests'])
        assert out.stdout.strip().split('\n')[-1].startswith(f'{n}/{n}'), (cid, out.stdout[-500:])
        cases.append({'id': cid, 'prompt': prompt, 'expected': tests,
                      'notes': f"[{spec['d']}] " + notes_extra.get(cid, '') + f" Reference solution: coding/{group_dir}/{cid}/ref.js (passes {n}/{n}); tests generated by coding/{group_dir}/{cid}/gen.mjs. Every example in the prompt was re-checked against the reference."})
    return cases


def mean_tokens(cases):
    return int(sum(tok(c['prompt']) for c in cases) / len(cases)) + 30
