// Central tuning. Every number that shapes how the game *feels* lives here so
// balancing is one file, not a scavenger hunt. Distances are metres, time is
// seconds, angles are radians — the render layer converts metres → pixels.

export const SIM = {
  dt: 1 / 120, // fixed physics step (s). We integrate at 120Hz for stable bounces.
  gravity: 12.5, // m/s² — slightly punchier than real gravity so lofted play reads well
}

// Pitch is a compact, arena-style small-sided field (think 3v3/6v6), which keeps
// the action dense and the physics legible.
export const FIELD = {
  length: 58, // x-axis, goal to goal
  width: 38, // y-axis, touchline to touchline
  margin: 6, // run-off around the pitch that the camera can see
  goalWidth: 7.2, // mouth width (along y)
  goalHeight: 2.6, // crossbar height (z)
  goalDepth: 2.2, // how deep the net sits behind the line
  centerRadius: 6,
  boxDepth: 12, // penalty area depth from the goal line
  boxWidth: 24, // penalty area width
  cornerRadius: 0.9,
}

export const BALL = {
  radius: 0.34,
  mass: 0.43,
  groundFriction: 1.9, // rolling deceleration (m/s²-ish, applied as linear damping)
  airDrag: 0.14, // per-second velocity damping while airborne
  restitution: 0.62, // vertical bounciness off the turf
  spinDecay: 1.3, // how fast spin bleeds off per second
  magnus: 0.9, // strength of the sideways curve force from spin
  maxSpeed: 46, // hard cap so a mishit can't launch to the moon
  settleSpeed: 0.35, // below this it's treated as "at rest"
}

export const PLAYER = {
  radius: 0.62,
  reach: 1.5, // how far in front the ball can be while still "controlled"
  walkSpeed: 3.4,
  runSpeed: 6.0,
  sprintSpeed: 8.4,
  accel: 34, // m/s² — responsive but momentum still matters
  decel: 28,
  turnRate: 11, // rad/s the heading can slew (momentum on direction changes)
  staminaMax: 100,
  sprintDrain: 14, // stamina/s while sprinting
  pressDrain: 9, // extra stamina/s while actively pressing
  slideDrain: 20, // one-off cost of a slide tackle
  staminaRegen: 8, // stamina/s recovered when not sprinting
  tiredFactor: 0.72, // speed multiplier when fully gassed
}

// Kick model. Power (0..1) scales between min and max release speed. Passing,
// shooting and clearances share the model but differ in ceilings and loft.
export const KICK = {
  passMin: 9,
  passMax: 26,
  shotMin: 16,
  shotMax: 34,
  throughBias: 1.06, // through balls carry a touch more weight
  loftAngle: 0.62, // launch pitch (rad) for a full lofted ball
  chipAngle: 0.9, // steeper, softer chip over a keeper
  maxSpinFromAim: 10, // side-spin generated by aiming across the body
  firstTouchError: 0.12, // base positional error on a first touch (m), scaled by pace
  // Touch distances are tuned to stay INSIDE the control reach — a sprinting
  // touch pushes the ball near the edge (riskier) but keepable, not lost.
  dribbleTouch: 0.65, // base distance the ball is pushed ahead when dribbling
  sprintTouchBonus: 0.55, // heavier touch (further ahead) while sprinting = more risk
  chargeRate: 1.35, // how fast the power meter fills per second held
}

export const DEFEND = {
  tackleRange: 1.7,
  tackleWindow: 0.28, // timing window (s) where a standing tackle wins cleanly
  slideRange: 3.0,
  slideRecovery: 0.9, // seconds the slider is grounded/exposed after a slide
  interceptRadius: 1.1, // moving into this radius of a loose/passed ball claims it
  foulChance: 0.28, // mistimed challenges can concede a free kick
}

export const GK = {
  reach: 2.6, // dive reach beyond the keeper's body
  diveSpeed: 13,
  speed: 6.5,
  rushSpeed: 7.4,
  lineDepth: 1.4, // resting distance off the goal line
  catchPower: 24, // shots slower than this can be caught cleanly (else parried)
  reactionError: 0.18, // fraction of shots that beat a well-positioned keeper
}

export const MATCH = {
  defaultHalfLength: 120, // seconds per half (arena-paced)
  kickoffDelay: 1.2,
  afterGoalDelay: 2.4,
  restartDelay: 0.8,
}

// Two team liveries. Purely cosmetic — no attribute differences (no pay-to-win).
export interface Kit {
  name: string
  primary: string
  secondary: string
  accent: string
  gk: string
}

export const KITS: Record<'home' | 'away', Kit> = {
  home: { name: 'Riverside', primary: '#2f7df6', secondary: '#eaf1ff', accent: '#0b2d63', gk: '#f6c945' },
  away: { name: 'Lakeside', primary: '#ec4d4d', secondary: '#2a0d0d', accent: '#7a1414', gk: '#33d6a6' },
}
