// Hidden tests for c6; every expected value comes from ref.js and is re-checked by brute.py.
import fs from 'node:fs';
import { rng, load, deepEqual, python } from '../lib.mjs';
import { randomEvents } from './events.mjs';
const ref = load('./c6/ref.js', 'runExchange');
const R = rng(777);
const T = [];
const add = (label, events) => T.push({ label, args: [events] });
const L = (id, s, p, q) => ['LIMIT', id, s, p, q], I = (id, s, p, q, k) => ['ICEBERG', id, s, p, q, k], M = (id, s, q) => ['MARKET', id, s, q];
const S = (id, s, t, q) => ['STOP', id, s, t, q], C = (id) => ['CANCEL', id], A = (id, p, q) => ['AMEND', id, p, q];
add('limit order sweeps several price levels, remainder rests', [L(1, 'SELL', 101, 5), L(2, 'SELL', 100, 3), L(3, 'SELL', 103, 4), L(4, 'BUY', 102, 10), L(5, 'BUY', 99, 1)]);
add('time priority within a price level', [L(1, 'BUY', 50, 4), L(2, 'BUY', 50, 4), L(3, 'BUY', 51, 1), L(4, 'SELL', 50, 6), L(5, 'SELL', 52, 2)]);
add('market orders: partial fill and empty book', [M(1, 'BUY', 5), L(2, 'SELL', 10, 3), M(3, 'BUY', 5), L(4, 'BUY', 9, 2), M(5, 'SELL', 1)]);
add('iceberg refresh goes behind orders at the same price', [I(1, 'BUY', 100, 30, 10), L(2, 'BUY', 100, 5), M(3, 'SELL', 25), L(4, 'BUY', 100, 1)]);
add('iceberg refreshes repeatedly against one big order', [I(1, 'SELL', 20, 23, 4), L(2, 'BUY', 20, 22)]);
add('incoming iceberg trades its full size, then shows only its peak', [L(1, 'SELL', 70, 6), L(2, 'SELL', 71, 6), I(3, 'BUY', 71, 40, 5), L(4, 'SELL', 72, 3)]);
add('partially filled iceberg display is not refilled early', [I(1, 'SELL', 30, 50, 10), M(2, 'BUY', 7), L(3, 'SELL', 30, 5), M(4, 'BUY', 5), M(5, 'BUY', 4)]);
add('iceberg with peak larger than its quantity', [I(1, 'BUY', 40, 6, 100), L(2, 'BUY', 40, 2), M(3, 'SELL', 7)]);
add('stop order triggers right after its own submission', [L(1, 'SELL', 100, 5), L(2, 'BUY', 100, 1), L(3, 'SELL', 101, 5), S(4, 'BUY', 100, 3), S(5, 'BUY', 102, 1)]);
add('stop cascade in submission order', [L(1, 'SELL', 10, 1), L(2, 'SELL', 11, 1), L(3, 'SELL', 12, 1), L(4, 'SELL', 13, 1), S(5, 'BUY', 11, 1), S(6, 'BUY', 10, 1), S(7, 'BUY', 13, 1), L(8, 'BUY', 10, 1)]);
add('re-check after each stop: an earlier-triggerable stop may stop qualifying', [L(1, 'SELL', 100, 1), L(2, 'BUY', 99, 5), L(3, 'SELL', 105, 5), S(4, 'BUY', 100, 2), S(5, 'SELL', 101, 2), L(6, 'BUY', 100, 1)]);
add('stops are not checked in the middle of a sweep', [L(1, 'SELL', 98, 1), L(2, 'SELL', 99, 1), L(3, 'SELL', 100, 1), S(4, 'SELL', 99, 1), L(5, 'BUY', 90, 2), L(6, 'BUY', 100, 3)]);
add('stops wait for the first trade; a cancelled stop never fires; triggered stops can meet an empty book', [S(1, 'SELL', 1000, 5), S(2, 'BUY', 1, 5), S(3, 'BUY', 5, 1), C(2), L(4, 'BUY', 7, 1), L(5, 'SELL', 7, 1)]);
add('cancel: resting, unknown, already filled, market id', [L(1, 'BUY', 5, 3), L(2, 'BUY', 5, 3), M(3, 'SELL', 3), C(1), C(3), C(42), C(2), L(4, 'SELL', 4, 1)]);
add('amend: reduce keeps priority, increase loses it', [L(1, 'BUY', 60, 5), L(2, 'BUY', 60, 5), L(3, 'BUY', 60, 5), A(1, 60, 2), A(2, 60, 9), M(4, 'SELL', 8)]);
add('amend: price change crosses and trades as the incoming order', [L(1, 'SELL', 80, 4), L(2, 'BUY', 75, 6), A(2, 81, 6), L(3, 'SELL', 81, 3)]);
add('amend is ignored for icebergs, stops, unknown and filled ids', [I(1, 'BUY', 30, 20, 5), S(2, 'SELL', 10, 4), L(3, 'SELL', 31, 2), M(4, 'BUY', 2), A(1, 31, 5), A(2, 20, 1), A(3, 32, 9), A(99, 1, 1), L(5, 'SELL', 30, 6)]);
add('amend of a partially filled order to the same size is a no-op', [L(1, 'SELL', 12, 10), L(2, 'SELL', 12, 10), M(3, 'BUY', 4), A(1, 12, 6), A(2, 12, 11), M(4, 'BUY', 9)]);
add('amended order can be amended again and triggers a stop', [L(1, 'BUY', 50, 5), S(2, 'BUY', 52, 3), L(3, 'SELL', 55, 10), L(4, 'SELL', 53, 1), A(1, 51, 5), A(1, 53, 4), L(5, 'SELL', 60, 1)]);
add('book levels show only displayed iceberg quantity', [I(1, 'SELL', 10, 100, 7), I(2, 'SELL', 10, 9, 20), L(3, 'SELL', 11, 4), I(4, 'BUY', 8, 50, 3), L(5, 'BUY', 8, 2), L(6, 'BUY', 7, 1)]);
add('sell stop cascade pushes the price down through bids', [L(1, 'BUY', 99, 2), L(2, 'BUY', 98, 2), L(3, 'BUY', 97, 2), L(4, 'BUY', 90, 50), S(5, 'SELL', 98, 3), S(6, 'SELL', 97, 4), S(7, 'SELL', 91, 1), M(8, 'SELL', 3)]);
add('triggered stop consumes the book and leaves the rest unfilled', [L(1, 'SELL', 5, 1), S(2, 'BUY', 5, 10), L(3, 'BUY', 5, 1), L(4, 'SELL', 6, 2)]);
for (let i = 0; i < 6; i++) add(`random stream #${i + 1}`, randomEvents(R, [60, 100, 150, 200, 250, 300][i], { spread: [3, 5, 8, 4, 10, 6][i], maxQty: [10, 20, 50, 15, 30, 25][i] }));
add('large stream, tight prices', randomEvents(R, 1500, { spread: 6, maxQty: 30, mid: 500 }));
add('large stream, wide prices', randomEvents(R, 2000, { spread: 300, maxQty: 100, mid: 100000 }));
const tests = T.map((t) => ({ args: t.args, expected: ref(...t.args) }));
const py = python('./c6/brute.py', T.map((t) => t.args));
let bad = 0;
tests.forEach((t, i) => { if (!deepEqual(t.expected, py[i])) { bad++; console.log('MISMATCH', T[i].label); } });
T.forEach((t, i) => console.log(String(i + 1).padStart(2), t.label.padEnd(76), 'trades', String(tests[i].expected.trades.length).padStart(4), 'bids', tests[i].expected.bids.length, 'asks', tests[i].expected.asks.length, 'stops', tests[i].expected.stops.length));
console.log(bad ? `${bad} MISMATCHES` : `all ${tests.length} tests agree with brute.py`);
fs.writeFileSync(new URL('./tests.json', import.meta.url), JSON.stringify({ functionName: 'runExchange', tests }));
fs.writeFileSync(new URL('./labels.json', import.meta.url), JSON.stringify(T.map((t) => t.label)));
console.log('json bytes', JSON.stringify(tests).length);
