'use strict';

/**
 * @deprecated Flat-rate estimate used by the 2019 audit export only.
 * Nothing in the payroll imports this module any more; it is kept so old audit
 * files can still be regenerated byte-for-byte. Do not "fix" it: the numbers
 * must match what was filed in 2019.
 */
function estimateTax2019(grossCents) {
  // The 2019 estimate deliberately ignored the tax-free band.
  return Math.floor(grossCents * 0.22);
}

function estimateNet2019(grossCents, pensionPct = 0) {
  const pension = Math.floor((grossCents * pensionPct) / 100);
  return grossCents - pension - estimateTax2019(grossCents);
}

module.exports = { estimateTax2019, estimateNet2019 };
