import json, itertools
from gen import gen
from explore import CFG, NAMES7
import truthlib
from truthlib import stmt_text, NUMW, consistent

PICKS = [
    ('c01', 'e3', 13, 'easy'),
    ('c02', 'e4', 12, 'easy'),
    ('c03', 'm5', 13, 'medium'),
    ('c04', 'm5', 11, 'medium'),
    ('c05', 'm4a', 10, 'medium'),
    ('c06', 'm5s', 11, 'medium'),
    ('c07', 'h5a', 10, 'hard'),
    ('c08', 'h6', 10, 'hard'),
    ('c09', 'h6s', 10, 'hard'),
    ('c10', 'h6s', 12, 'hard'),
    ('c11', 'x6all', 10, 'extreme'),
    ('c12', 'x7a', 12, 'extreme'),
    ('c13', 'x6s2', 12, 'extreme'),
    ('c14', 'x7s', 11, 'extreme'),
    ('c15', 'x6s2', 11, 'extreme'),
]

GLOBAL_TEXT = {
    'e3': None, 'e4': None, 'm5': None, 'h6': None,
    'm5s': 'Exactly one of them is a spy.',
    'h6s': 'Exactly one of them is a spy.',
    'x6s2': 'Exactly two of them are spies.',
    'x7s': 'At most one of them is a spy (there may be no spy at all).',
    'm4a': None, 'h5a': None, 'x7a': None,
    'x6all': 'Exactly one of them is a spy and exactly one of them is an alternator.',
}

TYPE_DEF = {
    'knight': '- A knight: every statement a knight makes is true.',
    'knave': '- A knave: every statement a knave makes is false.',
    'spy': '- A spy: each statement a spy makes may be true or false, in any combination.',
    'alternator': '- An alternator: an alternator\'s statements alternate between true and false in the order they are made. The first may be either true or false, but no two consecutive statements by an alternator have the same truth value.',
}


def build_case(cid, cfgname, seed, diff):
    c = dict(CFG[cfgname])
    n = c.pop('n'); types = c.pop('types'); glob = c.pop('glob')
    w, stmts = gen(n, types, glob, seed, **c)
    names = NAMES7[:n]
    truthlib.META_SINGLE.clear()
    for i, l in enumerate(stmts):
        truthlib.META_SINGLE[i] = len(l) == 1
    worlds = [x for x in itertools.product(types, repeat=n) if glob(x) and consistent(x, stmts)]
    assert worlds == [w], (cid, worlds)
    lines = []
    for s, lst in enumerate(stmts):
        if len(lst) == 1:
            lines.append(f'{names[s]} says: "{stmt_text(lst[0], s, names)}"')
        else:
            parts = ' '.join(f'({i+1}) "{stmt_text(st, s, names)}"' for i, st in enumerate(lst))
            lines.append(f'{names[s]} makes {NUMW[len(lst)]} statements, in this order: {parts}')
    typelist = ', '.join(types[:-1]) + ' or ' + types[-1] if len(types) > 2 else ' or '.join(types)
    header = [f"On a certain island, every inhabitant is exactly one of these types:"]
    header += [TYPE_DEF[t] for t in types]
    who = ', '.join(names[:-1]) + ' and ' + names[-1]
    g = GLOBAL_TEXT[cfgname]
    intro = f"You meet {NUMW[n]} inhabitants: {who}. Each of them knows the type of everyone present."
    if g:
        intro += ' ' + g
    else:
        intro += ' There may be any number of each type among them, including none.'
    has_meta = any(st[0] == 'meta' for l in stmts for st in l)
    conv = [
        "Conventions:",
        f"- \"Us\" always means all {NUMW[n]} of these inhabitants, including the speaker.",
        "- \"Or\" is inclusive: \"P, or Q\" is true when at least one of P and Q is true.",
        "- \"P, and Q\" is true only when both P and Q are true.",
        "- \"If P, then Q\" is false only when P is true and Q is false; otherwise it is true.",
        "- \"P if and only if Q\" is true exactly when P and Q are both true or both false.",
        "- \"X and Y are the same type\" / \"different types\" compare the two people's types.",
        "- \"Among X, Y and me, exactly two are knights\" counts only the people named (\"me\" is the speaker).",
    ]
    if has_meta:
        conv.append("- A statement such as \"Ada's second statement is true\" refers to that person's statement with that number in the list below (\"Ada's statement\" when she made only one), and is true exactly when that statement is true.")
    types_words = ', '.join(types)
    ask = (
        "Determine the type of every inhabitant. There is exactly one assignment of types consistent with all of the information above.\n\n"
        f"Give your answer as a single line in exactly this form, listing everyone in the order they were introduced and using only the words {types_words}:\n"
        + ', '.join(f"{nm}: <type>" for nm in names) +
        "\nGive exactly one answer. If you give more than one answer, it will be marked wrong."
    )
    prompt = '\n'.join(header) + '\n\n' + intro + '\n\n' + '\n'.join(conv) + '\n\nStatements:\n' + '\n'.join(lines) + '\n\n' + ask
    labeled = ', '.join(f"{nm}: {t}" for nm, t in zip(names, w))
    plain = ', '.join(w)
    total_worlds = sum(1 for x in itertools.product(types, repeat=n) if glob(x))
    notes = (f"Generated by truth/gen.py config {cfgname} seed {seed}. Verified by exhaustive enumeration of all {total_worlds} type assignments "
             f"allowed by the global rule: exactly one ({labeled}) satisfies every speaker constraint. Independently re-verified by truth/verify.mjs, which parses the English statements in the prompt back into logic and brute-forces them.")
    return dict(id=cid, difficulty=diff, prompt=prompt, expected=[labeled, plain], notes=notes,
                ast=dict(names=names, types=types, stmts=stmts, solution=w, glob=g))


if __name__ == '__main__':
    out = [build_case(*p) for p in PICKS]
    json.dump(out, open('truth_cases.json', 'w'), indent=1)
    for c in out:
        print(c['id'], c['difficulty'], c['expected'][0])
    print(out[10]['prompt'])
