from fractions import Fraction as F
from itertools import product, combinations, permutations
import math
R={}
# C07b: five-digit multiples of 11 with digit sum 27
R['C07b']=sum(1 for n in range(10000,100000) if n%11==0 and sum(map(int,str(n)))==27)
alt=9*sum(1 for a in range(1,10) for c in range(10) for e in range(10) if a+c+e==19)
assert alt==R['C07b'], (alt,R['C07b'])

# C15: cube face colorings, adjacent faces different, up to rotation.
# faces: 0=U,1=D,2=F,3=B,4=L,5=R ; opposite pairs (0,1),(2,3),(4,5)
opp={0:1,1:0,2:3,3:2,4:5,5:4}
adj=[(i,j) for i in range(6) for j in range(i+1,6) if opp[i]!=j]
assert len(adj)==12
# rotation group generated by 90deg turns about vertical axis and about L-R axis
rotU=[0,1,4,5,3,2]   # face i moves to position rotU[i]: F->L? define as permutation of positions
rotR=[2,3,1,0,4,5]
def compose(p,q): return tuple(p[q[i]] for i in range(6))
G={tuple(range(6))}
frontier=[tuple(range(6))]
while frontier:
    g=frontier.pop()
    for h in (rotU,rotR):
        k=compose(tuple(h),g)
        if k not in G: G.add(k); frontier.append(k)
assert len(G)==24, len(G)
# verify each g preserves adjacency
for g in G:
    for (i,j) in adj:
        assert opp[g[i]]!=g[j]
def canon(col):
    best=None
    for g in G:
        c=[None]*6
        for i in range(6): c[g[i]]=col[i]
        c=tuple(c)
        if best is None or c<best: best=c
    return best
for k in (3,4,5):
    s=set(); s_exact4=set()
    tot=0
    for col in product(range(k),repeat=6):
        if all(col[i]!=col[j] for i,j in adj):
            tot+=1
            s.add(canon(col))
            if len(set(col))==4: s_exact4.add(canon(col))
    print('k',k,'proper',tot,'orbits',len(s),'exactly4 used',len(s_exact4))
    R[f'C15_k{k}']=len(s)

# C16: 12-gon, 4 random distinct vertices, P(center strictly inside convex quad)
pts=[(math.cos(2*math.pi*i/12),math.sin(2*math.pi*i/12)) for i in range(12)]
def strictly_inside(idx):
    idx=sorted(idx)
    poly=[pts[i] for i in idx]
    # convex polygon in CCW order; center strictly inside iff all cross products > 0 (with tolerance)
    for a in range(len(poly)):
        x1,y1=poly[a]; x2,y2=poly[(a+1)%len(poly)]
        cr=(x2-x1)*(0-y1)-(y2-y1)*(0-x1)
        if cr<=1e-9: return False
    return True
fav=sum(1 for c in combinations(range(12),4) if strictly_inside(c))
p=F(fav,math.comb(12,4))
# combinatorial check: gaps all <=5
fav2=0
for c in combinations(range(12),4):
    gaps=[(c[(i+1)%4]-c[i])%12 for i in range(4)]
    if max(gaps)<=5: fav2+=1
assert fav==fav2
R['C16']=p.numerator+p.denominator; R['C16_frac']=p; R['C16_fav']=fav

# C17: triangle (0,0),(21,0),(5,12): OI^2
A=(F(0),F(0)); B=(F(21),F(0)); C=(F(5),F(12))
def d2(P,Q): return (P[0]-Q[0])**2+(P[1]-Q[1])**2
a2,b2,c2=d2(B,C),d2(C,A),d2(A,B)
a,b,c=[math.isqrt(int(x)) for x in (a2,b2,c2)]
assert a*a==a2 and b*b==b2 and c*c==c2
I=((a*A[0]+b*B[0]+c*C[0])/(a+b+c),(a*A[1]+b*B[1]+c*C[1])/(a+b+c))
# circumcenter
ax,ay=A; bx,by=B; cx,cy=C
d=2*(ax*(by-cy)+bx*(cy-ay)+cx*(ay-by))
ux=((ax**2+ay**2)*(by-cy)+(bx**2+by**2)*(cy-ay)+(cx**2+cy**2)*(ay-by))/d
uy=((ax**2+ay**2)*(cx-bx)+(bx**2+by**2)*(ax-cx)+(cx**2+cy**2)*(bx-ax))/d
OI2=d2((ux,uy),I)
R['C17']=OI2.numerator+OI2.denominator; R['C17_frac']=OI2
print(R)
