#!/usr/bin/env python3
"""
Rebuild src/ui/fonts.css from the source faces in scripts/fonts/.

The app embeds its typefaces as base64 rather than linking them, because the
standalone single-file build has to work from file:// with no assets beside it.
That makes every byte of font data a byte of the HTML file, so the faces are
subset to the glyphs this app can actually render instead of shipping the whole
latin range.

The character set is DERIVED, not guessed: every string literal in src/ plus
every string value in the catalogue and pricing data, which together cover all
static copy and every part, game and vendor name. Full printable ASCII and the
Latin-1 letters are added on top as a safety margin for text a user types in —
a part name pasted from a listing, a saved-build label. A glyph outside that set
falls back to the system font, which looks slightly off but never breaks.

Italic is deliberately NOT shipped. The whole app renders exactly two <em>
elements; a 24KB face for two words is a bad trade, and browsers synthesise a
perfectly serviceable oblique from the regular weight.

Requires: pip install fonttools brotli
Run:      python3 scripts/build-fonts.py
"""
import base64
import glob
import json
import os
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONTS = os.path.join(ROOT, 'scripts', 'fonts')
OUT = os.path.join(ROOT, 'src', 'ui', 'fonts.css')


def charset() -> set[str]:
    chars: set[str] = set()
    for f in glob.glob(os.path.join(ROOT, 'src', '**', '*.ts*'), recursive=True):
        chars |= set(open(f, encoding='utf-8').read())
    for pat in ('data/catalogue/*.json', 'data/pricing/*.json', 'data/fixtures/*.json'):
        for f in glob.glob(os.path.join(ROOT, pat)):
            def walk(v):
                if isinstance(v, str):
                    chars.update(v)
                elif isinstance(v, list):
                    for x in v: walk(x)
                elif isinstance(v, dict):
                    for x in v.values(): walk(x)
            walk(json.load(open(f, encoding='utf-8')))
    used = {c for c in chars if c.isprintable() and ord(c) > 31}
    used |= {chr(c) for c in range(0x20, 0x7F)}          # all printable ASCII
    used |= {chr(c) for c in range(0xA0, 0x100)}          # Latin-1, for typed input
    return used


def subset(src: str, dst: str, text: str) -> None:
    subprocess.run(
        [sys.executable, '-m', 'fontTools.subset', src,
         f'--text-file={text}', '--flavor=woff2', f'--output-file={dst}',
         # Keep the features the design depends on: tabular figures line the
         # numeric columns up, and the kerning/ligature tables are what make the
         # type look bought rather than defaulted.
         '--layout-features=kern,liga,clig,calt,tnum,zero,frac',
         '--no-hinting', '--desubroutinize'],
        check=True, capture_output=True)


def main() -> None:
    used = charset()
    sources = json.load(open(os.path.join(FONTS, 'sources.json')))
    latin = ("U+0000-00FF, U+0131, U+0152-0153, U+2000-206F, U+20AC, U+2122, "
             "U+2191-2193, U+2212, U+2264-2265, U+2713, U+2715, U+2630, U+FEFF, U+FFFD")

    with tempfile.TemporaryDirectory() as tmp:
        txt = os.path.join(tmp, 'chars.txt')
        open(txt, 'w', encoding='utf-8').write(''.join(sorted(used)))

        blocks = [
            '/* IBM Plex, subset to the glyphs this app renders and embedded so the',
            '   standalone single-file build keeps its typeface offline.',
            '   Generated by scripts/build-fonts.py — do not edit by hand.',
            f'   Charset: {len(used)} glyphs. Italic is synthesised, not shipped. */',
            '',
        ]
        before = after = 0
        for s in sources:
            if s['style'] == 'italic':
                before += os.path.getsize(os.path.join(FONTS, s['file']))
                continue
            src = os.path.join(FONTS, s['file'])
            dst = os.path.join(tmp, s['file'])
            subset(src, dst, txt)
            before += os.path.getsize(src)
            after += os.path.getsize(dst)
            w = s['weights']
            rng = f"{w[0]} {w[-1]}" if len(w) > 1 else w[0]
            b64 = base64.b64encode(open(dst, 'rb').read()).decode()
            blocks.append(
                f"@font-face {{\n"
                f"  font-family: '{s['family']}';\n"
                f"  font-style: {s['style']};\n"
                f"  font-weight: {rng};\n"
                f"  font-display: swap;\n"
                f"  src: url(data:font/woff2;base64,{b64}) format('woff2');\n"
                f"  unicode-range: {latin};\n"
                f"}}")

        open(OUT, 'w', encoding='utf-8').write('\n'.join(blocks) + '\n')
        css = os.path.getsize(OUT)
        print(f'charset      {len(used)} glyphs')
        print(f'font data    {before/1024:.0f}KB -> {after/1024:.0f}KB  ({100*(1-after/before):.0f}% smaller)')
        print(f'fonts.css    {css/1024:.0f}KB (base64 inflates by ~33%)')


if __name__ == '__main__':
    main()
