/**
 * Wave 3 entry point — parsers over the raw cache. No network, re-runnable.
 *
 * Two steps:
 *  1. The identity/alias parser (pci.ids plus the two driver tables).
 *  2. The specification parser: for every cached spec page in `cache/raw/`,
 *     run `src/parse/spec-mapper.ts` and write candidate records to
 *     `agents/out/parsed-<source>.json` in the same envelope shape the
 *     catalogue agents used, so `scripts/reconcile.ts` picks them up with no
 *     changes.
 *
 * Step 2 is a no-op today: every specification source is egress-blocked in this
 * environment (see cache/manifest.json), so nothing is cached to parse. That is
 * reported and the script exits 0 — an empty cache is a known state of the
 * world, not a failure.
 *
 * When those sources do become reachable, `npm run harvest && npm run parse`
 * will produce candidate records for the first time, and they should be
 * reviewed BEFORE `npm run reconcile` merges them: the mapping has never been
 * run against real markup. See agents/log/spec-mapper.md for exactly what to
 * check first.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Provenance } from '../src/core/types.ts';
import { parseSpecPage } from '../src/parse/spec-mapper.ts';
import { main as runAliasParser } from './parse-aliases.ts';

const ROOT = new URL('..', import.meta.url).pathname;
const RAW = join(ROOT, 'cache/raw');
const OUT = join(ROOT, 'agents/out');
const MANIFEST = join(ROOT, 'cache/manifest.json');

interface SpecSource {
  /** Matches the harvester's source id, so the cache path is `<id>.raw`. */
  id: string;
  kind: 'gpu' | 'cpu';
  vendor: 'nvidia' | 'amd' | 'intel';
}

/**
 * Cached pages this parser knows how to read. The ids mirror `scripts/harvest.ts`;
 * `wikipedia-intel-gpus` is declared ahead of the harvester so a manually cached
 * Arc page is picked up without a code change.
 */
const SPEC_SOURCES: SpecSource[] = [
  { id: 'wikipedia-nvidia-gpus', kind: 'gpu', vendor: 'nvidia' },
  { id: 'wikipedia-amd-gpus', kind: 'gpu', vendor: 'amd' },
  { id: 'wikipedia-intel-gpus', kind: 'gpu', vendor: 'intel' },
  { id: 'wikipedia-intel-cpus', kind: 'cpu', vendor: 'intel' },
  { id: 'wikipedia-amd-cpus', kind: 'cpu', vendor: 'amd' },
];

interface ManifestEntry {
  id: string;
  url?: string;
  licence?: string;
  status?: string;
  retrievedAt?: string;
}

function manifestEntry(id: string): ManifestEntry | undefined {
  if (!existsSync(MANIFEST)) return undefined;
  try {
    const m = JSON.parse(readFileSync(MANIFEST, 'utf8')) as { entries?: ManifestEntry[] };
    return (m.entries ?? []).find((e) => e.id === id);
  } catch {
    return undefined;
  }
}

/** Group skip reasons so the envelope's `gaps` is readable rather than a log dump. */
function summariseReasons(skipped: { reason: string }[]): string[] {
  const counts = new Map<string, number>();
  for (const s of skipped) counts.set(s.reason, (counts.get(s.reason) ?? 0) + 1);
  return [...counts.entries()]
    .sort((a, b) => b[1] - a[1])
    .map(([reason, count]) => `${count} row(s) skipped: ${reason}`);
}

function parseOne(source: SpecSource): { written: string; records: number; skipped: number } {
  const raw = readFileSync(join(RAW, `${source.id}.raw`), 'utf8');
  const report = parseSpecPage(raw, source.kind, { vendor: source.vendor, provenanceId: source.id });

  const entry = manifestEntry(source.id);
  const provenance: Record<string, Provenance> = {
    [source.id]: {
      id: source.id,
      source: `Cached specification page (${source.id})`,
      url: entry?.url ?? '',
      licence: entry?.licence ?? 'unknown — check cache/manifest.json',
      retrievedAt: (entry?.retrievedAt ?? new Date().toISOString()).slice(0, 10),
      note: 'Parsed by src/parse/spec-mapper.ts. Capability blocks and driver status are DERIVED from the architecture per agents/BRIEF.md, not stated by the page.',
    },
  };

  const dataRows = (report.tables ?? []).reduce((a, t) => a + t.dataRows, 0);
  const envelope = {
    agentId: `parsed-${source.id}`,
    kind: source.kind,
    provenance,
    records: report.records,
    expectedCount: dataRows,
    actualCount: report.records.length,
    gaps: [
      ...summariseReasons(report.skipped),
      ...(report.columnsMissing.length
        ? [`No column identified for: ${report.columnsMissing.join(', ')} — these fields are null on every record from this page.`]
        : []),
      ...(report.notes ?? []),
    ],
    uncertainties: [
      'The column-to-field mapping in src/parse/spec-mapper.ts has been tested against SYNTHETIC fixtures only; this may be its first contact with real markup.',
      'Ids are generated by slugify() and may not match hand-curated catalogue ids for a few parts (e.g. abbreviated variants) — check data/reconcile-report.json for duplicates and near-misses before trusting a merge.',
      'caps.* and driverStatus are rule-derived from the architecture, not read from the page.',
      'Records carrying _conflicts had a stated value dropped for being implausible or internally inconsistent; the dropped value is preserved there.',
    ],
    parseReport: {
      columnsFound: report.columnsFound,
      columnsMissing: report.columnsMissing,
      tables: report.tables,
      skipped: report.skipped,
      notes: report.notes,
    },
  };

  const path = join(OUT, `parsed-${source.id}.json`);
  writeFileSync(path, JSON.stringify(envelope, null, 2));
  return { written: `agents/out/parsed-${source.id}.json`, records: report.records.length, skipped: report.skipped.length };
}

function main() {
  // --- Step 1: identity/alias tables -------------------------------------
  if (existsSync(join(RAW, 'pci-ids.raw'))) {
    runAliasParser();
  } else {
    console.log('SKIP alias parser — cache/raw/pci-ids.raw missing. Run `npm run harvest` first.');
  }

  // --- Step 2: specification pages ---------------------------------------
  console.log('');
  const cached = SPEC_SOURCES.filter((s) => existsSync(join(RAW, `${s.id}.raw`)));

  if (!cached.length) {
    console.log('No specification pages are cached, so there is nothing for the spec parser to read.');
    console.log('Expected any of:');
    for (const s of SPEC_SOURCES) {
      const status = manifestEntry(s.id)?.status;
      console.log(`  cache/raw/${s.id}.raw${status ? `  [harvest status: ${status}]` : '  [not declared in cache/manifest.json]'}`);
    }
    console.log('');
    console.log('Every one of these sources is egress-blocked in this environment; the catalogue');
    console.log('therefore remains the model-knowledge seed. Re-run `npm run harvest` somewhere');
    console.log('unrestricted and this step will produce agents/out/parsed-*.json candidates.');
    return;
  }

  mkdirSync(OUT, { recursive: true });
  for (const s of cached) {
    const r = parseOne(s);
    console.log(`${s.id.padEnd(24)} ${String(r.records).padStart(5)} candidate record(s), ${r.skipped} row(s) skipped -> ${r.written}`);
  }
  console.log('');
  console.log('These are CANDIDATES from a mapping that has only ever been tested against synthetic');
  console.log('fixtures. Review agents/out/parsed-*.json (its parseReport block names every skipped');
  console.log('row and unmapped column) before running `npm run reconcile`.');
}

main();
