// Builds the Vision test library: renders every image (SVG → PNG in headless Chromium) into tests/vision/images/
// and writes the four test files into tests/vision/. Answer keys come from the generators, never by hand.
//
//   node verification/vision/build.mts            # rebuild tests + images
//   node verification/vision/build.mts --no-png   # rebuild only the JSON (keep the committed images)
//
// Re-rendering on a different Chromium or font set can change image bytes, which changes the test hash. Only
// re-render when you intend to publish a new version of these tests (bump "version" below when you do).
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildCharts, type VisionCase } from './charts.mts';
import { buildSpots } from './spot.mts';
import { buildHandwriting } from './handwriting.mts';
import { buildCounts } from './count.mts';
import { renderAll } from './lib.mts';

const here = dirname(fileURLToPath(import.meta.url));
const TESTS = join(here, '..', '..', 'tests', 'vision');
const IMAGES = join(TESTS, 'images');

interface Meta {
  slug: string;
  id: string;
  name: string;
  description: string;
  difficulty: 'easy' | 'medium' | 'hard' | 'extreme';
  tags: string[];
  hook: string;
  scorer: Record<string, unknown>;
  outputTokens: number;
  cases: VisionCase[];
  caseScorer?: (c: VisionCase) => Record<string, unknown> | undefined;
}

const TESTS_META: Meta[] = [
  {
    slug: 'read-the-chart',
    id: 'vision.read-the-chart',
    name: 'Read the Chart',
    description:
      'Six generated business and science charts (bar, pie, two-series line, stacked bars without value labels, a dual-axis climate chart and grouped bars). Every question needs the model to read exact values off the picture and then do arithmetic: the largest month-on-month rise, dollars from percentages, months where one line beats the other, the sum of unlabelled stacked segments, the right axis for the right series, and a rounded percentage growth with a trap for anyone who compares absolute gains.',
    difficulty: 'medium',
    tags: ['vision', 'charts', 'data-reading', 'arithmetic', 'generated'],
    hook: 'Six charts. Read the numbers, do the maths, no labels to lean on.',
    scorer: { type: 'number', tolerance: 0 },
    outputTokens: 3000,
    cases: buildCharts(),
    caseScorer: (c) => (Array.isArray(c.expected) ? { type: 'exact', normalize: 'alnum' } : undefined),
  },
  {
    slug: 'spot-the-difference',
    id: 'vision.spot-the-difference',
    name: 'Spot the Difference',
    description:
      'Two grids of coloured shapes side by side; the right one is a copy of the left with a few cells changed (colour, shape, size, a flipped triangle, a small white dot, or a missing or extra object). The model must list exactly the changed cells, and in one case name the kind of each change. Grids grow from 4×4 to 8×8. The whole list must be right: one missed or invented difference scores 0.',
    difficulty: 'hard',
    tags: ['vision', 'visual-comparison', 'attention-to-detail', 'generated'],
    hook: 'Find every difference. Miss one and it is zero.',
    scorer: { type: 'json', unorderedArrays: true, allOrNothing: true },
    outputTokens: 3000,
    cases: buildSpots(),
  },
  {
    slug: 'handwritten-maths',
    id: 'vision.handwritten-maths',
    name: 'Handwritten Maths',
    description:
      'Maths written by hand on lined paper: order of operations, a column addition, a linear equation, stacked fractions, a power and a square root, and a word problem in messy block capitals. The handwriting is a jittered single-stroke pen generated by code, so no image exists anywhere else. The model has to read every digit correctly and then compute a single integer.',
    difficulty: 'medium',
    tags: ['vision', 'handwriting', 'ocr', 'math', 'generated'],
    hook: 'Messy handwriting, exact answers.',
    scorer: { type: 'number', tolerance: 0 },
    outputTokens: 2000,
    cases: buildHandwriting(),
  },
  {
    slug: 'count-and-locate',
    id: 'vision.count-and-locate',
    name: 'Count & Locate',
    description:
      'Count one kind of object among look-alike distractors (same colour, other shape; same shape, other colour; triangles pointing the wrong way), or list the board cells that hold a target. The hard cases have fifty-odd shapes of mixed sizes and cells whose two shapes carry swapped colours. Counting must be exact.',
    difficulty: 'medium',
    tags: ['vision', 'counting', 'localisation', 'generated'],
    hook: 'How many? Where? Exactly.',
    scorer: { type: 'number', tolerance: 0 },
    outputTokens: 2500,
    cases: buildCounts(),
    caseScorer: (c) => (c.expected && typeof c.expected === 'object' && !Array.isArray(c.expected) ? { type: 'json', unorderedArrays: true, allOrNothing: true } : undefined),
  },
];

const renderPng = !process.argv.includes('--no-png');
mkdirSync(IMAGES, { recursive: true });
if (renderPng) await renderAll(TESTS_META.flatMap((t) => t.cases.map((c) => c.image)), IMAGES);

for (const t of TESTS_META) {
  const words = t.cases.reduce((s, c) => s + c.prompt.length, 0) / t.cases.length;
  const def = {
    kind: 'prompt',
    id: t.id,
    version: '1.0.0',
    name: t.name,
    category: 'vision',
    description: t.description,
    difficulty: t.difficulty,
    tags: t.tags,
    hook: t.hook,
    maxOutputTokens: 16000,
    // Text tokens only: image tokens are added per vendor by the cost estimator (see src/core/vision.ts).
    estimate: { inputTokens: Math.ceil(words / 3.8) + 40, outputTokens: t.outputTokens },
    author: 'Gauntlet Core',
    createdAt: '2026-09-24',
    scorer: t.scorer,
    cases: t.cases.map((c) => {
      const scorer = t.caseScorer?.(c);
      return { id: c.id, prompt: c.prompt, images: [`images/${c.image.file}`], expected: c.expected, ...(scorer ? { scorer } : {}), notes: c.notes };
    }),
  };
  writeFileSync(join(TESTS, `${t.slug}.json`), JSON.stringify(def, null, 2) + '\n');
  console.log(`${t.id}: ${t.cases.length} cases`);
}
console.log(renderPng ? `Rendered ${TESTS_META.reduce((s, t) => s + t.cases.length, 0)} images into ${IMAGES}` : 'Skipped PNG rendering (--no-png)');
