// "Count & Locate": count one kind of object among look-alike distractors, or list the grid cells that hold it.
// Scenes are placed by a seeded RNG; the key is counted from the same object list that is drawn.
import { createRng } from '../../src/core/rng.ts';
import type { Rng } from '../../src/core/types.ts';
import { COLORS, SHAPES, shape, svgDoc, text, type ShapeKind } from './lib.mts';
import type { VisionCase } from './charts.mts';

interface Placed {
  shape: ShapeKind;
  color: string;
  x: number;
  y: number;
  r: number;
  down: boolean;
}

const ONE = 'Give exactly one answer. If you give more than one answer, it will be marked wrong.';
const INT = 'Give the final answer as a single integer (digits only, no words or units).';

/** Scatter objects without overlap (minimum gap between outlines). */
function scatter(rng: Rng, n: number, W: number, H: number, top: number, radius: () => number, make: (i: number) => Omit<Placed, 'x' | 'y' | 'r'>): Placed[] {
  const out: Placed[] = [];
  let guard = 0;
  while (out.length < n) {
    if (++guard > 200000) throw new Error('scatter: canvas too crowded');
    const r = radius();
    const x = rng.int(40 + r, W - 40 - r);
    const y = rng.int(top + r, H - 30 - r);
    if (out.some((o) => Math.hypot(o.x - x, o.y - y) < o.r + r + 14)) continue;
    out.push({ ...make(out.length), x, y, r });
  }
  return out;
}

function draw(objs: Placed[]): string {
  return objs.map((o) => shape(o.shape, o.x, o.y, o.r, COLORS[o.color]!, { rotation: o.down ? 180 : 0 })).join('');
}

// k01 ─ count red triangles
function countRedTriangles(): VisionCase {
  const rng = createRng(14001);
  const W = 1200, H = 800;
  const target = rng.int(6, 10);
  const kinds: Array<Omit<Placed, 'x' | 'y' | 'r'>> = [];
  for (let i = 0; i < target; i++) kinds.push({ shape: 'triangle', color: 'red', down: false });
  for (let i = 0; i < 30 - target; i++) {
    const redOther = rng.chance(0.5);
    kinds.push(redOther ? { shape: rng.pick(SHAPES.filter((s) => s !== 'triangle')), color: 'red', down: false } : { shape: 'triangle', color: rng.pick(['blue', 'green', 'orange', 'purple']), down: false });
  }
  const order = rng.shuffle(kinds);
  const objs = scatter(rng, order.length, W, H, 100, () => 30, (i) => order[i]!);
  const count = objs.filter((o) => o.shape === 'triangle' && o.color === 'red').length;
  const svg = svgDoc(W, H, text(W / 2, 54, 'How many red triangles?', { size: 30, anchor: 'middle', weight: 800, fill: '#0f172a' }) + draw(objs));
  return {
    id: 'k01',
    prompt: `The image shows a scattered collection of coloured shapes. How many red triangles are there? Count only shapes that are both red and triangular.\n\n${INT} ${ONE}`,
    expected: count,
    notes: `[standard] ${objs.length} shapes, none overlapping. Red triangles: ${count}. Distractors: red non-triangles (${objs.filter((o) => o.color === 'red' && o.shape !== 'triangle').length}) and triangles of other colours (${objs.filter((o) => o.shape === 'triangle' && o.color !== 'red').length}). Generated by verification/vision/count.mts (seed 14001).`,
    image: { file: 'count-k01.png', svg, width: W, height: H },
    marks: { targets: objs.filter((o) => o.shape === 'triangle' && o.color === 'red').map((o) => ({ x: o.x, y: o.y, r: o.r })) },
  };
}

function gridFrame(n: number, x0: number, y0: number, size: number): string {
  const cell = size / n;
  let s = `<rect x="${x0}" y="${y0}" width="${size}" height="${size}" fill="#f8fafc" stroke="#334155" stroke-width="2.5"/>`;
  for (let i = 1; i < n; i++) {
    s += `<line x1="${x0 + cell * i}" y1="${y0}" x2="${x0 + cell * i}" y2="${y0 + size}" stroke="#cbd5e1" stroke-width="1.5"/>`;
    s += `<line x1="${x0}" y1="${y0 + cell * i}" x2="${x0 + size}" y2="${y0 + cell * i}" stroke="#cbd5e1" stroke-width="1.5"/>`;
  }
  for (let c = 0; c < n; c++) {
    s += text(x0 + cell * (c + 0.5), y0 - 12, String.fromCharCode(65 + c), { size: 20, anchor: 'middle', weight: 700, fill: '#334155' });
    s += text(x0 + cell * (c + 0.5), y0 + size + 28, String.fromCharCode(65 + c), { size: 20, anchor: 'middle', weight: 700, fill: '#334155' });
  }
  for (let r = 0; r < n; r++) {
    s += text(x0 - 14, y0 + cell * (r + 0.5) + 7, String(r + 1), { size: 20, anchor: 'end', weight: 700, fill: '#334155' });
    s += text(x0 + size + 14, y0 + cell * (r + 0.5) + 7, String(r + 1), { size: 20, anchor: 'start', weight: 700, fill: '#334155' });
  }
  return s;
}

const cellName = (c: number, r: number) => `${String.fromCharCode(65 + c)}${r + 1}`;

// k02 ─ locate green stars on an 8×8 board
function locateGreenStars(): VisionCase {
  const rng = createRng(14002);
  const n = 8, size = 640, x0 = 90, y0 = 100;
  const W = x0 * 2 + size, H = y0 + size + 60;
  const cells: Array<{ shape: ShapeKind; color: string } | null> = [];
  const targets = new Set<number>();
  const want = rng.int(4, 6);
  while (targets.size < want) targets.add(rng.int(0, n * n - 1));
  for (let i = 0; i < n * n; i++) {
    if (targets.has(i)) cells.push({ shape: 'star', color: 'green' });
    else if (rng.chance(0.12)) cells.push(null);
    else {
      // Look-alikes: stars of other colours and green shapes that are not stars.
      const k = rng.int(0, 2);
      if (k === 0) cells.push({ shape: 'star', color: rng.pick(['yellow', 'orange', 'blue', 'red']) });
      else if (k === 1) cells.push({ shape: rng.pick(SHAPES.filter((s) => s !== 'star')), color: 'green' });
      else cells.push({ shape: rng.pick(SHAPES.filter((s) => s !== 'star')), color: rng.pick(['yellow', 'orange', 'blue', 'red', 'purple']) });
    }
  }
  const cell = size / n;
  let s = gridFrame(n, x0, y0, size);
  cells.forEach((o, i) => {
    if (o) s += shape(o.shape, x0 + cell * ((i % n) + 0.5), y0 + cell * (Math.floor(i / n) + 0.5), cell * 0.34, COLORS[o.color]!);
  });
  const answer = [...targets].sort((a, b) => (a % n) - (b % n) || Math.floor(a / n) - Math.floor(b / n)).map((i) => cellName(i % n, Math.floor(i / n)));
  const svg = svgDoc(W, H, text(W / 2, 50, 'Find the green stars', { size: 28, anchor: 'middle', weight: 800, fill: '#0f172a' }) + s);
  return {
    id: 'k02',
    prompt: `The image shows an 8×8 board. Columns are labelled A–H (left to right) and rows 1–8 (top to bottom), so B3 is column B, row 3. Which cells contain a green star?\n\nEnd your reply with a JSON object in exactly this form, listing each cell once (any order): {"cells": ["A1", "C4"]}`,
    expected: { cells: answer },
    notes: `[standard] Green stars at ${answer.join(', ')}. Every other cell holds a non-green star, a green non-star, another shape or nothing. Generated by verification/vision/count.mts (seed 14002).`,
    image: { file: 'count-k02.png', svg, width: W, height: H },
    marks: { grids: [{ id: 'BOARD', x0, y0, size, n }] },
  };
}

// k03 ─ count blue triangles pointing down among many look-alikes, varied sizes
function countDownTriangles(): VisionCase {
  const rng = createRng(14003);
  const W = 1200, H = 860;
  const target = rng.int(7, 11);
  const kinds: Array<Omit<Placed, 'x' | 'y' | 'r'>> = [];
  for (let i = 0; i < target; i++) kinds.push({ shape: 'triangle', color: 'blue', down: true });
  const distract: Array<() => Omit<Placed, 'x' | 'y' | 'r'>> = [
    () => ({ shape: 'triangle', color: 'blue', down: false }),
    () => ({ shape: 'triangle', color: 'purple', down: true }),
    () => ({ shape: 'triangle', color: rng.pick(['green', 'orange', 'red']), down: rng.chance(0.5) }),
    () => ({ shape: rng.pick(['heart', 'star', 'hexagon'] as ShapeKind[]), color: 'blue', down: rng.chance(0.5) }),
  ];
  for (let i = 0; i < 52 - target; i++) kinds.push(rng.pick(distract)());
  const order = rng.shuffle(kinds);
  const objs = scatter(rng, order.length, W, H, 100, () => rng.int(16, 34), (i) => order[i]!);
  const count = objs.filter((o) => o.shape === 'triangle' && o.color === 'blue' && o.down).length;
  const svg = svgDoc(W, H, text(W / 2, 54, 'Blue triangles pointing down', { size: 30, anchor: 'middle', weight: 800, fill: '#0f172a' }) + draw(objs));
  return {
    id: 'k03',
    prompt: `The image shows a crowded collection of coloured shapes of different sizes; some triangles point up and some point down. How many shapes are blue triangles pointing down (one corner at the bottom, flat side on top)? Count only shapes that are blue, triangular and pointing down.\n\n${INT} ${ONE}`,
    expected: count,
    notes: `[hard] ${objs.length} shapes (radius 16-34 px, none overlapping). Blue down-triangles: ${count}. Distractors: blue up-triangles ${objs.filter((o) => o.shape === 'triangle' && o.color === 'blue' && !o.down).length}, purple down-triangles ${objs.filter((o) => o.shape === 'triangle' && o.color === 'purple' && o.down).length}, other triangles and blue non-triangles. Generated by verification/vision/count.mts (seed 14003).`,
    image: { file: 'count-k03.png', svg, width: W, height: H },
    marks: { targets: objs.filter((o) => o.shape === 'triangle' && o.color === 'blue' && o.down).map((o) => ({ x: o.x, y: o.y, r: o.r })) },
  };
}

// k04 ─ cells holding BOTH a yellow circle and a purple square (with swapped-colour traps)
function locatePairs(): VisionCase {
  const rng = createRng(14004);
  const n = 9, size = 720, x0 = 90, y0 = 100;
  const W = x0 * 2 + size, H = y0 + size + 60;
  type Item = { shape: ShapeKind; color: string };
  const cells: Item[][] = [];
  const targets = new Set<number>();
  const want = rng.int(4, 6);
  while (targets.size < want) targets.add(rng.int(0, n * n - 1));
  const yc: Item = { shape: 'circle', color: 'yellow' };
  const ps: Item = { shape: 'square', color: 'purple' };
  const isTarget = (items: Item[]) => items.some((i) => i.shape === 'circle' && i.color === 'yellow') && items.some((i) => i.shape === 'square' && i.color === 'purple');
  for (let i = 0; i < n * n; i++) {
    if (targets.has(i)) {
      cells.push(rng.shuffle([yc, ps]));
      continue;
    }
    let items: Item[];
    do {
      const k = rng.int(0, 4);
      if (k === 0) items = rng.shuffle([{ shape: 'circle', color: 'purple' }, { shape: 'square', color: 'yellow' }]); // swapped colours
      else if (k === 1) items = rng.shuffle([yc, { shape: rng.pick(SHAPES.filter((s) => s !== 'square')), color: rng.pick(['purple', 'blue', 'green', 'red']) }]);
      else if (k === 2) items = rng.shuffle([ps, { shape: rng.pick(SHAPES.filter((s) => s !== 'circle')), color: rng.pick(['yellow', 'orange', 'green', 'red']) }]);
      else if (k === 3) items = [{ shape: rng.pick(SHAPES), color: rng.pick(Object.keys(COLORS)) }];
      else items = rng.shuffle([{ shape: 'circle', color: 'orange' }, { shape: 'square', color: rng.pick(['purple', 'blue']) }]);
    } while (isTarget(items));
    cells.push(items);
  }
  const cell = size / n;
  let s = gridFrame(n, x0, y0, size);
  cells.forEach((items, i) => {
    const cx = x0 + cell * ((i % n) + 0.5);
    const cy = y0 + cell * (Math.floor(i / n) + 0.5);
    if (items.length === 1) s += shape(items[0]!.shape, cx, cy, cell * 0.3, COLORS[items[0]!.color]!);
    else items.forEach((it, k) => (s += shape(it.shape, cx + (k ? 1 : -1) * cell * 0.22, cy, cell * 0.19, COLORS[it.color]!)));
  });
  const answer = [...targets].sort((a, b) => (a % n) - (b % n) || Math.floor(a / n) - Math.floor(b / n)).map((i) => cellName(i % n, Math.floor(i / n)));
  const svg = svgDoc(W, H, text(W / 2, 50, 'Yellow circle + purple square', { size: 28, anchor: 'middle', weight: 800, fill: '#0f172a' }) + s);
  return {
    id: 'k04',
    prompt: `The image shows a 9×9 board. Columns are labelled A–I (left to right) and rows 1–9 (top to bottom), so B3 is column B, row 3. Each cell holds one or two shapes. List every cell that contains BOTH a yellow circle AND a purple square.\n\nEnd your reply with a JSON object in exactly this form, listing each cell once (any order): {"cells": ["A1", "C4"]}`,
    expected: { cells: answer },
    notes: `[hard] Target cells: ${answer.join(', ')}. Traps: purple circle + yellow square (${cells.filter((c) => c.length === 2 && c.some((i) => i.shape === 'circle' && i.color === 'purple') && c.some((i) => i.shape === 'square' && i.color === 'yellow')).length} cells), a yellow circle or a purple square with something else, orange circle + square. Generated by verification/vision/count.mts (seed 14004).`,
    image: { file: 'count-k04.png', svg, width: W, height: H },
    marks: { grids: [{ id: 'BOARD', x0, y0, size, n }] },
  };
}

export function buildCounts(): VisionCase[] {
  return [countRedTriangles(), locateGreenStars(), countDownTriangles(), locatePairs()];
}
