// "Handwritten Maths": sums, equations and a word problem written in a jittered single-stroke hand on lined paper.
// Numbers are drawn from a seeded RNG and every answer is computed from those numbers.
import { createRng } from '../../src/core/rng.ts';
import type { Rng } from '../../src/core/types.ts';
import { GLYPHS, handLine, handwrite, paper, smoothPath, svgDoc, type Hand, type Pt } from './lib.mts';
import type { VisionCase } from './charts.mts';

const W = 1200;
const INK = '#1e3a8a';
const ONE = 'Give exactly one answer. If you give more than one answer, it will be marked wrong.';
const INT = 'Give the final answer as a single integer (digits only, no words or units).';

function hand(seed: number, mess: number, strokeWidth = 4.2): Hand {
  return { rng: createRng(seed), mess, ink: INK, strokeWidth };
}

/** Approximate written width of a string (for centring numerators over fraction bars). */
function measure(s: string, size: number): number {
  let w = 0;
  for (const ch of s) w += ch === ' ' ? size * 0.42 : ((GLYPHS[ch]?.w ?? 0.5) + 0.2) * size;
  return w;
}

function gcd(a: number, b: number): number {
  return b ? gcd(b, a % b) : a;
}

function image(id: string, height: number, body: string, lineGap = 96, top = 150): VisionCase['image'] {
  return { file: `hand-${id}.png`, svg: svgDoc(W, height, paper(W, height, lineGap, top) + body, '#fdfcf7'), width: W, height };
}

// h01 ─ order of operations
function orderOfOps(): VisionCase {
  const rng = createRng(13001);
  const a = rng.int(21, 89), b = rng.int(12, 49), c = rng.int(3, 9);
  const h = hand(13101, 0.35);
  const size = 70;
  const [svg] = handwrite(h, `${a} + ${b} * ${c} = ?`, 160, 246 - size, size);
  return {
    id: 'h01',
    prompt: `The image shows a handwritten arithmetic problem. Work it out using the usual order of operations (multiplication and division before addition and subtraction).\n\n${INT} ${ONE}`,
    expected: a + b * c,
    notes: `[standard] Written: ${a} + ${b} × ${c} = ?. Answer ${a} + ${b * c} = ${a + b * c} (left-to-right evaluation would give ${(a + b) * c}). Generated by verification/vision/handwriting.mts (seed 13001, hand 13101).`,
    image: image('h01', 420, svg),
  };
}

// h02 ─ column addition
function columnAddition(): VisionCase {
  const rng = createRng(13002);
  const nums = [rng.int(1200, 9800), rng.int(1200, 9800), rng.int(1200, 9800)];
  const h = hand(13102, 0.4);
  const size = 64;
  const right = 700;
  let svg = '';
  nums.forEach((n, i) => {
    const s = String(n);
    const baseline = 246 + i * 96;
    svg += handwrite(h, s, right - measure(s, size), baseline - size, size)[0];
  });
  svg += handwrite(h, '+', right - measure(String(nums[2]), size) - 110, 246 + 2 * 96 - size, size)[0];
  svg += handLine(h, right - measure('00000', size) - 40, 246 + 2 * 96 + 26, right + 20, 246 + 2 * 96 + 30);
  svg += handLine(h, right - measure('00000', size) - 40, 246 + 3 * 96 + 26, right + 20, 246 + 3 * 96 + 22);
  return {
    id: 'h02',
    prompt: `The image shows a handwritten column addition whose result has not been filled in yet. What is the sum of the three numbers?\n\n${INT} ${ONE}`,
    expected: nums[0]! + nums[1]! + nums[2]!,
    notes: `[standard] Written numbers: ${nums.join(' + ')} = ${nums[0]! + nums[1]! + nums[2]!}. Generated by verification/vision/handwriting.mts (seed 13002, hand 13102).`,
    image: image('h02', 620, svg),
  };
}

// h03 ─ linear equation
function linearEquation(): VisionCase {
  const rng = createRng(13003);
  let x = 0, a = 0, b = 0, c = 0, d = 0;
  do {
    x = rng.int(6, 19);
    a = rng.int(4, 9);
    c = rng.int(2, a - 1);
    b = rng.int(5, 39);
    d = (a - c) * x - b;
  } while (d < 3 || d > 60);
  const h = hand(13103, 0.4);
  const size = 70;
  const [svg] = handwrite(h, `${a}x - ${b} = ${c}x + ${d}`, 160, 246 - size, size);
  return {
    id: 'h03',
    prompt: `The image shows a handwritten equation with one unknown, x. Solve it: what is the value of x?\n\n${INT} ${ONE}`,
    expected: x,
    notes: `[standard] Written: ${a}x − ${b} = ${c}x + ${d}. Then ${a - c}x = ${d + b}, so x = ${x}. Generated by verification/vision/handwriting.mts (seed 13003, hand 13103).`,
    image: image('h03', 420, svg),
  };
}

// h04 ─ stacked fractions
function fractions(): VisionCase {
  const rng = createRng(13004);
  const dens = [3, 4, 5, 6, 8];
  let p = 0, q = 0, r = 0, s = 0, m = 0, value = 0;
  do {
    q = rng.pick(dens);
    s = rng.pick(dens.filter((x) => x !== q));
    p = rng.int(1, q - 1);
    r = rng.int(1, s - 1);
    const l = (q * s) / gcd(q, s);
    m = l * rng.int(1, 2);
    value = (p * m) / q + (r * m) / s;
  } while (gcd(p, q) !== 1 || gcd(r, s) !== 1 || m > 48 || !Number.isInteger(value));
  const h = hand(13104, 0.4);
  const size = 70;
  const fs = 56;
  const base = 330; // baseline of the main line (fraction bars sit a bit above it)
  const barY = base - size * 0.42;
  let x = 150;
  let svg = '';
  const put = (str: string, sz = size, yTop = base - size) => {
    const [g, w] = handwrite(h, str, x, yTop, sz);
    svg += g;
    x += w;
  };
  const frac = (num: number, den: number) => {
    const w = Math.max(measure(String(num), fs), measure(String(den), fs)) + 30;
    svg += handwrite(h, String(num), x + (w - measure(String(num), fs)) / 2, barY - 16 - fs, fs)[0];
    svg += handLine(h, x, barY, x + w, barY);
    svg += handwrite(h, String(den), x + (w - measure(String(den), fs)) / 2, barY + 18, fs)[0];
    x += w + 16;
  };
  put('(');
  x += 6;
  frac(p, q);
  put('+');
  x += 10;
  frac(r, s);
  put(')');
  x += 14;
  put('*');
  put(` ${m} = ?`);
  return {
    id: 'h04',
    prompt: `The image shows a handwritten expression with two stacked fractions inside brackets, multiplied by a whole number. What is its value?\n\n${INT} ${ONE}`,
    expected: value,
    notes: `[hard] Written: (${p}/${q} + ${r}/${s}) × ${m} = ${(p * m) / q} + ${(r * m) / s} = ${value}. Generated by verification/vision/handwriting.mts (seed 13004, hand 13104).`,
    image: image('h04', 520, svg, 96, 150),
  };
}

// h05 ─ power, square root and division
function powerRoot(): VisionCase {
  const rng = createRng(13005);
  const base = rng.pick([2, 3]);
  const exp = base === 2 ? rng.int(5, 7) : rng.int(3, 4);
  const div = rng.int(3, 6);
  const root = div * rng.int(2, 4);
  const value = base ** exp - root / div;
  const h = hand(13105, 0.5);
  const size = 72;
  const baseline = 300;
  let x = 150;
  let svg = '';
  const put = (str: string, sz = size, yTop = baseline - sz) => {
    const [g, w] = handwrite(h, str, x, yTop, sz);
    svg += g;
    x += w;
  };
  put(String(base));
  x += 2;
  put(String(exp), 38, baseline - size - 30);
  x += 18;
  put('-');
  x += 8;
  // Radical sign drawn as one pen stroke, with the roof over the radicand.
  const rad = String(root * root);
  const rw = measure(rad, size) + 18;
  const top = baseline - size - 16;
  const pts: Pt[] = [[x, baseline - size * 0.45], [x + 14, baseline - size * 0.52], [x + 30, baseline + 4], [x + 50, top], [x + 58 + rw, top]];
  const jit = pts.map(([px, py]): Pt => [px + (h.rng.next() * 2 - 1) * 2, py + (h.rng.next() * 2 - 1) * 2]);
  svg += `<path d="${smoothPath(jit)}" fill="none" stroke="${INK}" stroke-width="4.2" stroke-linecap="round" stroke-linejoin="round"/>`;
  x += 62;
  put(rad);
  x += 18;
  put(`/ ${div} = ?`);
  return {
    id: 'h05',
    prompt: `The image shows a handwritten expression with a power (a small raised exponent), a square root and a division sign. Work it out using the usual order of operations.\n\n${INT} ${ONE}`,
    expected: value,
    notes: `[hard] Written: ${base}^${exp} − √${root * root} ÷ ${div} = ${base ** exp} − ${root}/${div} = ${value}. Generated by verification/vision/handwriting.mts (seed 13005, hand 13105).`,
    image: image('h05', 460, svg),
  };
}

// h06 ─ word problem in messy block capitals
function wordProblem(): VisionCase {
  const rng: Rng = createRng(13006);
  const trays = rng.int(12, 16);
  const per = rng.int(12, 24);
  const bags = rng.int(4, 9);
  const each = rng.int(6, 15);
  const sold = trays * per - bags * each;
  if (sold <= 0) throw new Error('h06: bad numbers');
  const lines = [`A BAKER MAKES ${trays} TRAYS OF ${per} ROLLS.`, `SHE SELLS ${sold} ROLLS AND SHARES THE`, `REST EQUALLY BETWEEN ${bags} BAGS.`, 'HOW MANY ROLLS GO IN EACH BAG?'];
  const h = hand(13106, 0.75, 3.6);
  const size = 40;
  let svg = '';
  lines.forEach((line, i) => {
    const baseline = 150 + 80 * i - 8;
    svg += handwrite(h, line, 120, baseline - size, size)[0];
  });
  return {
    id: 'h06',
    prompt: `The image shows a handwritten word problem in capital letters. Solve it.\n\n${INT} ${ONE}`,
    expected: each,
    notes: `[standard] Written: "${lines.join(' ')}" → ${trays} × ${per} = ${trays * per} rolls; ${trays * per} − ${sold} = ${bags * each} left; ÷ ${bags} = ${each}. Messier hand than the other cases, but every character stays legible. Generated by verification/vision/handwriting.mts (seed 13006, hand 13106).`,
    image: image('h06', 480, svg, 80, 150),
  };
}

export function buildHandwriting(): VisionCase[] {
  return [orderOfOps(), columnAddition(), linearEquation(), fractions(), powerRoot(), wordProblem()];
}
