// "Handwritten Maths": a student's worked solutions (find the first mistake), crossed-out corrections, a European hand,
// subscripts, fractions, powers and a messy word problem, written in a jittered single-stroke hand on lined paper.
// Numbers are drawn from a seeded RNG and every answer is computed from those numbers.
import { createRng } from '../../src/core/rng.ts';
import type { Rng } from '../../src/core/types.ts';
import { GLYPHS, crossOut, handLine, handwrite, paper, smoothPath, svgDoc, type Hand, type Pt } from './lib.mts';
import type { VisionCase } from './charts.mts';

const W = 1200;
const INK = '#1e3a8a';
const ONE = 'Give exactly one answer. If you give more than one answer, it will be marked wrong.';
const INT = 'Give the final answer as a single integer (digits only, no words or units).';

function hand(seed: number, mess: number, strokeWidth = 4.2): Hand {
  return { rng: createRng(seed), mess, ink: INK, strokeWidth };
}

/** Approximate written width of a string (for centring numerators over fraction bars). */
function measure(s: string, size: number): number {
  let w = 0;
  for (const ch of s) w += ch === ' ' ? size * 0.42 : ((GLYPHS[ch]?.w ?? 0.5) + 0.2) * size;
  return w;
}

function gcd(a: number, b: number): number {
  return b ? gcd(b, a % b) : a;
}

function image(id: string, height: number, body: string, lineGap = 96, top = 150): VisionCase['image'] {
  return { file: `hand-${id}.png`, svg: svgDoc(W, height, paper(W, height, lineGap, top) + body, '#fdfcf7'), width: W, height };
}

// h07 ─ stacked fractions
function fractions(): VisionCase {
  const rng = createRng(13004);
  const dens = [3, 4, 5, 6, 8];
  let p = 0, q = 0, r = 0, s = 0, m = 0, value = 0;
  do {
    q = rng.pick(dens);
    s = rng.pick(dens.filter((x) => x !== q));
    p = rng.int(1, q - 1);
    r = rng.int(1, s - 1);
    const l = (q * s) / gcd(q, s);
    m = l * rng.int(1, 2);
    value = (p * m) / q + (r * m) / s;
  } while (gcd(p, q) !== 1 || gcd(r, s) !== 1 || m > 48 || !Number.isInteger(value));
  const h = hand(13104, 0.4);
  const size = 70;
  const fs = 56;
  const base = 330; // baseline of the main line (fraction bars sit a bit above it)
  const barY = base - size * 0.42;
  let x = 150;
  let svg = '';
  const put = (str: string, sz = size, yTop = base - size) => {
    const [g, w] = handwrite(h, str, x, yTop, sz);
    svg += g;
    x += w;
  };
  const frac = (num: number, den: number) => {
    const w = Math.max(measure(String(num), fs), measure(String(den), fs)) + 30;
    svg += handwrite(h, String(num), x + (w - measure(String(num), fs)) / 2, barY - 16 - fs, fs)[0];
    svg += handLine(h, x, barY, x + w, barY);
    svg += handwrite(h, String(den), x + (w - measure(String(den), fs)) / 2, barY + 18, fs)[0];
    x += w + 16;
  };
  put('(');
  x += 6;
  frac(p, q);
  put('+');
  x += 10;
  frac(r, s);
  put(')');
  x += 14;
  put('*');
  put(` ${m} = ?`);
  return {
    id: 'h07',
    prompt: `The image shows a handwritten expression with two stacked fractions inside brackets, multiplied by a whole number. What is its value?\n\n${INT} ${ONE}`,
    expected: value,
    notes: `[standard] Written: (${p}/${q} + ${r}/${s}) × ${m} = ${(p * m) / q} + ${(r * m) / s} = ${value}. Generated by verification/vision/handwriting.mts (seed 13004, hand 13104).`,
    image: image('h07', 520, svg, 96, 150),
  };
}

// h08 ─ power, square root and division
function powerRoot(): VisionCase {
  const rng = createRng(13005);
  const base = rng.pick([2, 3]);
  const exp = base === 2 ? rng.int(5, 7) : rng.int(3, 4);
  const div = rng.int(3, 6);
  const root = div * rng.int(2, 4);
  const value = base ** exp - root / div;
  const h = hand(13105, 0.5);
  const size = 72;
  const baseline = 300;
  let x = 150;
  let svg = '';
  const put = (str: string, sz = size, yTop = baseline - sz) => {
    const [g, w] = handwrite(h, str, x, yTop, sz);
    svg += g;
    x += w;
  };
  put(String(base));
  x += 2;
  put(String(exp), 38, baseline - size - 30);
  x += 18;
  put('-');
  x += 8;
  // Radical sign drawn as one pen stroke, with the roof over the radicand.
  const rad = String(root * root);
  const rw = measure(rad, size) + 18;
  const top = baseline - size - 16;
  const pts: Pt[] = [[x, baseline - size * 0.45], [x + 14, baseline - size * 0.52], [x + 30, baseline + 4], [x + 50, top], [x + 58 + rw, top]];
  const jit = pts.map(([px, py]): Pt => [px + (h.rng.next() * 2 - 1) * 2, py + (h.rng.next() * 2 - 1) * 2]);
  svg += `<path d="${smoothPath(jit)}" fill="none" stroke="${INK}" stroke-width="4.2" stroke-linecap="round" stroke-linejoin="round"/>`;
  x += 62;
  put(rad);
  x += 18;
  put(`/ ${div} = ?`);
  return {
    id: 'h08',
    prompt: `The image shows a handwritten expression with a power (a small raised exponent), a square root and a division sign. Work it out using the usual order of operations.\n\n${INT} ${ONE}`,
    expected: value,
    notes: `[standard] Written: ${base}^${exp} − √${root * root} ÷ ${div} = ${base ** exp} − ${root}/${div} = ${value}. Generated by verification/vision/handwriting.mts (seed 13005, hand 13105).`,
    image: image('h08', 460, svg),
  };
}


const JSON_END = (example: string) => `End your reply with a JSON object in exactly this form: ${example}`;

/** Handwritten "(n)" line labels in the margin, left of the red line. */
function lineLabel(h: Hand, n: number, baseline: number): string {
  return handwrite(h, `(${n})`, 18, baseline - 30, 30)[0];
}

function reroll<T>(rng: Rng, make: (rng: Rng) => T | null): T {
  for (let i = 0; i < 10000; i++) {
    const v = make(rng);
    if (v !== null) return v;
  }
  throw new Error('handwriting generator could not satisfy its constraints');
}

const signed = (v: number) => (v < 0 ? `- ${-v}` : `+ ${v}`);

// h01 ─ a student's worked equation with one wrong step: find the first wrong line and the true solution
function equationError(): VisionCase {
  const p = reroll(createRng(13201), (rng) => {
    const a = rng.int(4, 9), c = rng.int(2, a - 2), b = rng.int(2, 9), x = rng.int(3, 14);
    const d = (a - c) * x - a * b; // a(x - b) = cx + d
    if (d === 0 || Math.abs(d) > 60) return null;
    const errLine = rng.pick([2, 3, 4]);
    let l2 = `${a}x - ${a * b} = ${c}x ${signed(d)}`;
    let rhs = d + a * b;
    let coef = a - c;
    if (errLine === 2) {
      l2 = `${a}x - ${b} = ${c}x ${signed(d)}`; // forgot to multiply b by a
      rhs = d + b;
    } else if (errLine === 3) rhs = d - a * b; // moved -ab across without changing sign
    else coef = a + c; // subtracted cx as if adding
    const l3 = `${a}x - ${c}x = ${d} ${errLine === 3 ? `- ${a * b}` : `+ ${errLine === 2 ? b : a * b}`}`;
    if (rhs % coef !== 0 || rhs / coef === x || rhs <= 0) return null;
    return { a, b, c, d, x, errLine, lines: [`${a}(x - ${b}) = ${c}x ${signed(d)}`, l2, l3, `${coef}x = ${rhs}`, `x = ${rhs / coef}`] };
  });
  const h = hand(13301, 0.45, 3.8);
  const size = 46;
  let svg = '';
  p.lines.forEach((line, i) => {
    const baseline = 150 + 80 * i - 8;
    svg += lineLabel(h, i + 1, baseline) + handwrite(h, line, 130, baseline - size, size)[0];
  });
  return {
    id: 'h01',
    prompt: `The image shows a student's handwritten solution of an equation, with the lines numbered (1) to (5) in the margin. Line (1) is the equation to solve and is copied correctly. Exactly one later line contains the student's first mistake; every line after it follows on from that mistake. Which line contains the first mistake, and what is the correct value of x for the equation in line (1)?\n\n${JSON_END('{"line": 3, "x": 12}')}`,
    expected: { line: p.errLine, x: p.x },
    notes: `[hard] Lines: ${p.lines.join(' | ')}. Correct working: ${p.a}x - ${p.a * p.b} = ${p.c}x ${signed(p.d)} → ${p.a - p.c}x = ${p.d + p.a * p.b} → x = ${p.x}. First wrong line: (${p.errLine}). Generated by verification/vision/handwriting.mts (seed 13201, hand 13301).`,
    image: image('h01', 560, svg, 80, 150),
    marks: { lines: p.lines.map((_, i) => ({ key: String(i + 1), y: 150 + 80 * i - 8 - 66, h: 80 })) },
  };
}

// h02 ─ long multiplication with one wrong partial product or sum
function multiplicationError(): VisionCase {
  const p = reroll(createRng(13202), (rng) => {
    const m = rng.int(213, 897), n = rng.int(23, 89);
    if (n % 10 === 0 || n % 10 === 1) return null;
    const u = m * (n % 10), t = m * (n - (n % 10));
    const errLine = rng.pick([3, 4, 5]);
    const bump = rng.pick([-3, -2, -1, 1, 2, 3]) * (errLine === 4 ? 100 : 10); // a middle digit is wrong
    const wu = errLine === 3 ? u + bump : u;
    const wt = errLine === 4 ? t + bump : t;
    const sum = errLine === 5 ? wu + wt + bump : wu + wt;
    if (wu <= 0 || wt <= 0 || String(wt).slice(-1) !== '0') return null;
    return { m, n, u, t, errLine, rows: [String(m), String(n), String(wu), String(wt), String(sum)] };
  });
  const h = hand(13302, 0.45, 3.8);
  const size = 50;
  const right = 640;
  let svg = '';
  p.rows.forEach((row, i) => {
    const baseline = 150 + 80 * i - 8;
    svg += lineLabel(h, i + 1, baseline) + handwrite(h, row, right - measure(row, size), baseline - size, size)[0];
    if (i === 1) svg += handwrite(h, '*', right - measure('000000', size) - 20, baseline - size, size)[0];
    if (i === 1 || i === 3) svg += handLine(h, right - measure('000000', size) - 30, baseline + 18, right + 20, baseline + 20);
  });
  return {
    id: 'h02',
    prompt: `The image shows a student's handwritten long multiplication, with the lines numbered (1) to (5) in the margin: line (1) times line (2), the two partial products in lines (3) and (4), and their sum in line (5). Lines (1) and (2) are copied correctly. Exactly one of lines (3), (4) and (5) is wrong (a later line may add up a wrong line correctly). Which line is wrong, and what is the correct product of line (1) and line (2)?\n\n${JSON_END('{"line": 4, "product": 12345}')}`,
    expected: { line: p.errLine, product: p.m * p.n },
    notes: `[hard] Written: ${p.rows.join(' | ')}. Correct: ${p.m} × ${p.n % 10} = ${p.u}, ${p.m} × ${p.n - (p.n % 10)} = ${p.t}, product ${p.m * p.n}. Wrong line: (${p.errLine}). Generated by verification/vision/handwriting.mts (seed 13202, hand 13302).`,
    image: image('h02', 560, svg, 80, 150),
    marks: { lines: p.rows.map((_, i) => ({ key: String(i + 1), y: 150 + 80 * i - 8 - 66, h: 80 })) },
  };
}

// h03 ─ shopping list with crossed-out prices and a crossed-out item
function crossedOutList(): VisionCase {
  const names = ['MILK', 'BREAD', 'EGGS', 'APPLES', 'RICE', 'COFFEE', 'CHEESE'];
  const rng = createRng(13203);
  const items = rng.shuffle(names).slice(0, 6).map((name) => ({ name, cents: rng.int(95, 899), fixed: 0, removed: false }));
  const fix = rng.shuffle([0, 1, 2, 3, 4, 5]);
  items[fix[0]!]!.fixed = items[fix[0]!]!.cents + rng.pick([-60, -35, 40, 75]);
  items[fix[1]!]!.fixed = items[fix[1]!]!.cents + rng.pick([-45, 25, 50, 110]);
  items[fix[2]!]!.removed = true;
  const cur = (it: (typeof items)[number]) => (it.removed ? 0 : it.fixed || it.cents);
  const total = items.reduce((s, it) => s + cur(it), 0);
  const money = (c: number) => `${Math.floor(c / 100)}.${String(c % 100).padStart(2, '0')}`;
  const h = hand(13303, 0.5, 3.8);
  const size = 42;
  let svg = handwrite(h, 'SHOPPING', 130, 110 - size, size)[0];
  items.forEach((it, i) => {
    const baseline = 150 + 70 * (i + 1) - 8;
    const [nameSvg] = handwrite(h, it.name, 130, baseline - size, size);
    const priceX = 520;
    const [priceSvg, pw] = handwrite(h, money(it.cents), priceX, baseline - size, size);
    svg += nameSvg + priceSvg;
    if (it.fixed) {
      svg += crossOut(h, priceX, baseline - size, priceX + pw, baseline);
      svg += handwrite(h, money(it.fixed), priceX + pw + 30, baseline - size, size)[0];
    }
    if (it.removed) svg += crossOut(h, 120, baseline - size, priceX + pw, baseline);
  });
  svg += handwrite(h, 'TOTAL = ?', 130, 150 + 70 * 7 - 8 - size, size)[0];
  return {
    id: 'h03',
    prompt: `The image shows a handwritten shopping list with corrections. Where a price is crossed out, the price written next to it replaces it; a line that is crossed out completely has been removed from the list. What is the total of the list as it now stands?\n\nGive the final answer as a single number with two decimals (for example 12.30), no currency sign. ${ONE}`,
    expected: total / 100,
    notes: `[hard] Items: ${items.map((it) => `${it.name} ${money(it.cents)}${it.fixed ? `→${money(it.fixed)}` : ''}${it.removed ? ' (removed)' : ''}`).join(', ')}. Total ${money(total)}. Generated by verification/vision/handwriting.mts (seed 13203, hand 13303).`,
    image: image('h03', 700, svg, 70, 150),
  };
}

// h04 ─ a European hand (long-flagged 1, crossed 7): the correct worked example shows how this person writes
function europeanDigits(): VisionCase {
  const rng = createRng(13204);
  const A = rng.pick([717, 771, 711, 777]);
  const B = rng.pick([17, 71, 11, 77].filter((b) => b < A));
  const C = rng.pick([7, 11, 17]);
  const D = rng.pick([71, 17, 117]);
  const value = (A - B) * C + D;
  const h: Hand = { ...hand(13304, 0.45), variants: { '1': '1e', '7': '7e' }, slant: 0.2 };
  const size = 58;
  let svg = handwrite(h, '17 + 71 = 88', 130, 180 - size, size)[0];
  svg += handwrite(h, `(${A} - ${B}) * ${C} + ${D} = ?`, 130, 340 - size, size)[0];
  return {
    id: 'h04',
    prompt: `The image shows two lines of handwritten arithmetic by the same person. The first line is a correct worked example; it shows how this person writes their digits. Work out the value of the expression on the second line (multiplication before addition and subtraction).\n\n${INT} ${ONE}`,
    expected: value,
    notes: `[hard] European-style hand: 1 is drawn as a long upstroke with no foot (it can look like an uncrossed 7) and 7 carries a crossbar. Calibration line 17 + 71 = 88 (correct). Written: (${A} − ${B}) × ${C} + ${D} = ${A - B} × ${C} + ${D} = ${value}. Generated by verification/vision/handwriting.mts (seed 13204, hand 13304).`,
    image: image('h04', 460, svg, 80, 180),
  };
}

// h05 ─ a recurrence written with subscripts
function recurrence(): VisionCase {
  const rng = createRng(13205);
  const a1 = rng.int(2, 5), k = rng.pick([2, 3]), c = rng.pick([-1, 1, -2, 2]);
  const target = k === 2 ? 6 : 5;
  const seq = [a1];
  while (seq.length < target) seq.push(k * seq[seq.length - 1]! + c);
  const h = hand(13305, 0.45);
  const size = 60, sub = 34;
  let svg = '';
  let x = 150;
  const put = (s: string, sz: number, top: number) => {
    const [g, w] = handwrite(h, s, x, top, sz);
    svg += g;
    x += w;
  };
  const baseline1 = 190, baseline2 = 310, baseline3 = 430;
  put('a', size, baseline1 - size);
  put('1', sub, baseline1 - sub + 14);
  put(` = ${a1}`, size, baseline1 - size);
  x = 150;
  put('a', size, baseline2 - size);
  put('n+1', sub, baseline2 - sub + 14);
  put(` = ${k}a`, size, baseline2 - size);
  put('n', sub, baseline2 - sub + 14);
  put(` ${c < 0 ? '-' : '+'} ${Math.abs(c)}`, size, baseline2 - size);
  x = 150;
  put('a', size, baseline3 - size);
  put(String(target), sub, baseline3 - sub + 14);
  put(' = ?', size, baseline3 - size);
  return {
    id: 'h05',
    prompt: `The image shows a handwritten sequence definition using subscripts (small numbers and letters written below the line), and a question on the last line. What is the answer to the question?\n\n${INT} ${ONE}`,
    expected: seq[target - 1]!,
    notes: `[hard] Written: a_1 = ${a1}; a_(n+1) = ${k}·a_n ${c < 0 ? '−' : '+'} ${Math.abs(c)}; a_${target} = ?. Sequence: ${seq.join(', ')}. Generated by verification/vision/handwriting.mts (seed 13205, hand 13305).`,
    image: image('h05', 520, svg, 120, 190),
  };
}

// h06 ─ a three-step word problem in messy, crowded block capitals
function messyWordProblem(): VisionCase {
  const p = reroll(createRng(13206), (rng) => {
    const start = rng.int(23, 68), packs = rng.int(3, 8), per = rng.pick([12, 15, 16, 24]), more = rng.int(13, 39);
    if ((start + packs * per) % 2) return null;
    return { start, packs, per, more, answer: (start + packs * per) / 2 + more };
  });
  const lines = [`TOM HAS ${p.start} STAMPS. HE BUYS ${p.packs} PACKS`, `OF ${p.per} AND GIVES HALF OF ALL HIS`, `STAMPS TO HIS SISTER. THEN HE BUYS`, `${p.more} MORE. HOW MANY DOES HE HAVE NOW?`];
  const h: Hand = { ...hand(13306, 1, 3.4), gap: 0.02, slant: 0.22 };
  const size = 40;
  let svg = '';
  lines.forEach((line, i) => {
    const baseline = 150 + 80 * i - 6;
    svg += handwrite(h, line, 115, baseline - size, size)[0];
  });
  return {
    id: 'h06',
    prompt: `The image shows a word problem handwritten quickly in crowded capital letters. Solve it.\n\n${INT} ${ONE}`,
    expected: p.answer,
    notes: `[hard] Written: "${lines.join(' ')}" → ${p.start} + ${p.packs} × ${p.per} = ${p.start + p.packs * p.per}; half = ${(p.start + p.packs * p.per) / 2}; + ${p.more} = ${p.answer}. Messy, tightly spaced hand. Generated by verification/vision/handwriting.mts (seed 13206, hand 13306).`,
    image: image('h06', 480, svg, 80, 150),
  };
}

export function buildHandwriting(): VisionCase[] {
  return [equationError(), multiplicationError(), crossedOutList(), europeanDigits(), recurrence(), messyWordProblem(), fractions(), powerRoot()];
}
